### ISSUE TITLE
Organization Import get unauthorized error 

### ISSUE THREAD

**Issue by fabianboerner** [pulumi/pulumi-mongodbatlas#240] opened 2023-07-03 23:01 UTC
### What happened?

executing:

```
pulumi import mongodbatlas:index/organization:Organization test xxxxxxx
```
```
 error: Preview failed: refreshing urn:pulumi:deployment::xxxxx::mongodbatlas:index/organization:Organization::test: 1 error occurred:
        * error deleting organization information: GET https://cloud.mongodb.com/api/atlas/v1.0/orgs/xxxxxx: 401 (request "") You are not authorized for this resource.
```

### Expected Behavior

Import successful

### Steps to reproduce

run

```
pulumi import mongodbatlas:index/organization:Organization test xxxxxx
```

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
command       0.7.2
gcp           6.59.0
mongodbatlas  3.9.0
nodejs        unknown
tls           4.10.0

Host     
OS       ubuntu
Version  18.04
Arch     x86_64

....

Dependencies:
NAME                  VERSION
@pulumi/command       0.7.2
@pulumi/gcp           6.59.0
@pulumi/mongodbatlas  3.9.0
@pulumi/pulumi        3.74.0
@pulumi/tls           4.10.0
@types/node           16.18.36

### Additional context

used the env variables and the config to set public and private key.

I pretty much gave every permission to the API Key

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment] 2023-07-06 18:22
Hi @fabianboerner, can you verify that you're able to create resources in the same stack as you're running the import?

**Comment by mikhailshilkov** [comment] 2023-09-14 09:59
@fabianboerner Do you have an update for the question that @AaronFriel asked above? It does seem like a permission error to me.

**Comment by mikhailshilkov** [comment] 2023-09-25 22:24
Since we have heard back, I'll assume the issue is not relevant anymore and close it. Feel free to report back if you still need help here. Thank you!

**Comment by fabianboerner** [comment] 2023-09-27 22:41
I was only now able to continue with this topic.

Still happens and yes the rest of the resource creation and importing works

Now at:

CLI          
Version      3.85.0

**Comment by mjeffryes** [comment] 2024-09-27 04:04
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)

**Closed** 2024-12-06 22:03 UTC
Labels: kind/bug, resolution/no-repro
