### ISSUE TITLE
Invalid address to set: []string{"snapshot_backup_policy", "0", "policies", "0", "id"}

### ISSUE THREAD

**Issue by adam-kiss-sg** [pulumi/pulumi-mongodbatlas#126] opened 2022-05-05 09:27 UTC
### What happened?

After creating a standard AWS cluster, i got the following error:

```
Invalid address to set: []string{"snapshot_backup_policy", "0", "policies", "0", "id"}
```

### Steps to reproduce

```
        cluster = mongodbatlas.Cluster(
            "cluster",
            name="my-cluster",
            project_id=project.id,
            provider_name="AWS",
            provider_instance_size_name="M10",
            cluster_type="REPLICASET",
            mongo_db_major_version="5.0",
            auto_scaling_disk_gb_enabled=True,
            cloud_backup=True,
            # provider_backup_enabled=True,
            replication_specs=[
                mongodbatlas.ClusterReplicationSpecArgs(
                    num_shards=1,
                    regions_configs=[
                        mongodbatlas.ClusterReplicationSpecRegionsConfigArgs(
                            electable_nodes=3,
                            priority=7,
                            read_only_nodes=0,
                            region_name="US_EAST_1",
                        )
                    ],
                )
            ],
            opts=pulumi.ResourceOptions(parent=self, depends_on=[network_container]),
        )
```

### Expected Behavior

No error

### Actual Behavior

got 

```
Invalid address to set: []string{"snapshot_backup_policy", "0", "policies", "0", "id"}
```

### Versions used

$ pulumi about
CLI          
Version      3.31.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.3.0
mongodbatlas  3.3.0
python        unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python (/home/.../.venv/bin/python3 v3.8.10)

Current Stack: dev

TYPE                                                  URN
pulumi:pulumi:Stack                                   urn:pulumi:dev::my-project::pulumi:pulumi:Stack::my-project-dev
pulumi:providers:aws                                  urn:pulumi:dev::my-project::pulumi:providers:aws::default
pkg:index:RootComponent                               urn:pulumi:dev::my-project::pkg:index:RootComponent::mongodb
pulumi:providers:mongodbatlas                         urn:pulumi:dev::my-project::pulumi:providers:mongodbatlas::mongodbatlas_provider
mongodbatlas:index/project:Project                    urn:pulumi:dev::my-project::pkg:index:RootComponent$mongodbatlas:index/project:Project::project
mongodbatlas:index/networkContainer:NetworkContainer  urn:pulumi:dev::my-project::pkg:index:RootComponent$mongodbatlas:index/networkContainer:NetworkContainer::network-container
mongodbatlas:index/cluster:Cluster                    urn:pulumi:dev::my-project::pkg:index:RootComponent$mongodbatlas:index/cluster:Cluster::my-cluster

Found no pending operations associated with dev

Backend        
Name           SG0166
URL            s3://my-bucket
User           my-user
Organizations  

NAME                 VERSION
black                22.3.0
flake8               4.0.1
pip                  20.0.2
pkg-resources        0.0.0
pulumi-aws           5.3.0
pulumi-mongodbatlas  3.3.0
setuptools           44.0.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by adam-kiss-sg** [comment] 2022-05-05 13:31
Finally found what causes this issue:

this repo uses a random commit form a random branch from forked version of the terraform provider:

```
	github.com/mongodb/terraform-provider-mongodbatlas => github.com/pulumi/terraform-provider-mongodbatlas v0.5.1-0.20220317190422-c0e974805834 // fork initiated to prevent duplicate ID from the TF plugin sdk
```
https://github.com/mongodb/terraform-provider-mongodbatlas/commit/c0e97480583428e5fc9b2dc90de7fcce89d7ab60

and this commit removes fields, breaking the whole thing :S

@guineveresaenger
currently both Cluster and AdvancedCluster are broken because of it

**Comment by kly630** [comment] 2022-05-09 18:52
I'm having the exact same problem trying to upgrade a cluster from version 1.7 to 3.3.  I can only get the project working be unsetting the "cloudBackup: true" field.  I obviously don't want to do that because we do need our clusters backed up.  I am using GCP for a provider and posted about this on the pulumi-community forums as well.  Happy to add any info if I can help or test.

**Comment by ljennia** [comment] 2022-06-23 16:47
Just ran into this issue but on a different resource:
```
error setting `certificates` for MongoDB X509 Authentication DB User(***): Invalid address to set: []string{"certificates", "0", "id"}
```

**Comment by adam-kiss-sg** [comment] 2022-06-24 11:14
If any1 is still running into this issue, you can revert to version 3.2.0 for now.

**Comment by tap1992** [comment] 2022-08-31 13:29
I am seeing this issue with a Azure cluster, blocking me from making changes to it or refreshing from it.
Downgrading to 3.2.0 doesn't appear to work either.

**Comment by gal-fordefi** [comment] 2022-09-13 15:03
> 3.2.0

Had to edit the state, set the provider version to `3.2.0`
`"version": "3.5.0" ->  "version": "3.2.0"`

**Comment by guineveresaenger** [comment] 2022-09-13 18:47
Hi everyone,

a bit of history: we had an error with duplicate ID fields a while back which is why those ID fields were removed in our fork. We've since fixed this bug: https://github.com/pulumi/pulumi-terraform-bridge/pull/507.

I've re-added the ID fields that were breaking everyone's stuff on [a patch branch](https://github.com/pulumi/terraform-provider-mongodbatlas/tree/upstream-v1.4.5-id-fix) on our fork (we still need this fork unfortunately due to other reasons).

It took me a minute to get a dupe of this due to account billing issues 😅 so thanks to @ljennia for chiming in with a much lighter resource that was also experiencing this issue.

Here's the error using current `pulumi up` for `X509AuthenticationDatabaseUser`:

```
     Type                                                  Name                  Status                  Info
 +   pulumi:pulumi:Stack                                   mongodbatlas-126-dev  **creating failed**     1 error
 +   ├─ mongodbatlas:index:Project                         guins-project         created                 
 +   ├─ mongodbatlas:index:DatabaseUser                    guin                  created               
 +   └─ mongodbatlas:index:X509AuthenticationDatabaseUser  guins-x509-auth       **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (mongodbatlas-126-dev):
    error: update failed
 
  mongodbatlas:index:X509AuthenticationDatabaseUser (guins-x509-auth):
    error: 1 error occurred:
    	* creating urn:pulumi:dev::mongodbatlas-126::mongodbatlas:index/x509AuthenticationDatabaseUser:X509AuthenticationDatabaseUser::guins-x509-auth: 1 error occurred:
    	* error setting `certificates` for MongoDB X509 Authentication DB User(guin-user): Invalid address to set: []string{"certificates", "0", "id"}
 
Resources:
    + 3 created

Duration: 9s
```

And now with the ID fields re-added and pulled into the provider:

```
     Type                                                  Name                  Status      Info
 +   pulumi:pulumi:Stack                                   mongodbatlas-126-dev  created     
 +   ├─ mongodbatlas:index:Project                         guins-project         created     
 +   ├─ mongodbatlas:index:DatabaseUser                    guin                  created     1 warning
 +   └─ mongodbatlas:index:X509AuthenticationDatabaseUser  guins-x509-auth       created     
 
Diagnostics:
  mongodbatlas:index:DatabaseUser (guin):
    warning: urn:pulumi:dev::mongodbatlas-126::mongodbatlas:index/databaseUser:DatabaseUser::guin verification warning: use auth_database_name instead
 
Outputs:
    id   : "12345"
    uname: "guin-user"

Resources:
    + 4 created

Duration: 9s
```

I'll be pushing this fix soon.

**Closed** 2022-09-15 00:48 UTC
Labels: kind/bug

**Comment by guineveresaenger** [comment] 2022-09-15 16:53
Hi friends,

please use v3.5.1 as the latest version that includes this fix going forward. 🙇‍♀️
